title: AEC Audio for ESPHome
description: Full-duplex AEC voice-audio component for ESPHome, built on the open-source Xiph SpeexDSP library
baseurl: ""
url: ""
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty
collections: {}
defaults:
- scope:
    path: ""
  values:
    layout: default
